import { motion } from 'framer-motion'
import { FiArrowUpRight, FiCheck, FiGithub, FiGlobe, FiLayers } from 'react-icons/fi'
import { featuredProject } from '../data/portfolioData'

function ProjectLink({ href, icon: Icon, children }) { return href ? <a className="button button-small" href={href} target="_blank" rel="noreferrer">{children} <Icon /></a> : <span className="button button-small is-disabled" aria-disabled="true">{children} <Icon /></span> }

function FeaturedProject() {
  return <section className="section featured-section" id="featured-project"><div className="container"><div className="featured-intro"><p className="eyebrow">05 / Featured project</p><span className="featured-index">01</span></div><div className="featured-header"><div><h2>{featuredProject.name}</h2><p className="project-kicker">{featuredProject.kicker}</p></div><p className="featured-description">{featuredProject.description}</p></div><div className="featured-body"><div className="case-notes"><div><span className="note-label">The problem</span><p>{featuredProject.problem}</p></div><div><span className="note-label">The solution</span><p>{featuredProject.solution}</p></div><div className="project-actions"><ProjectLink href={featuredProject.links.github} icon={FiGithub}>GitHub</ProjectLink><ProjectLink href={featuredProject.links.liveDemo} icon={FiGlobe}>Live demo</ProjectLink><ProjectLink href={featuredProject.links.caseStudy} icon={FiArrowUpRight}>Case study</ProjectLink></div></div><div className="architecture-panel"><div className="architecture-top"><span><FiLayers /> System architecture</span><span>COREVIA / FLOW</span></div><div className="architecture-flow">{featuredProject.architecture.map((item, index) => <motion.div className="architecture-node" key={item} initial={{ opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .06 }}><span className="node-number">{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong>{index < featuredProject.architecture.length - 1 && <span className="flow-line" />}</motion.div>)}</div></div></div><div className="feature-bottom"><div><span className="note-label">Key features</span><div className="feature-list">{featuredProject.features.map((feature) => <span key={feature}><FiCheck />{feature}</span>)}</div></div><div><span className="note-label">Technology</span><div className="technology-list">{featuredProject.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></div></div></div></section>
}
export default FeaturedProject
